Header done
korina0430/liftoff pull request #17
Opened 2021-03-19 03:33 UTC by Dhwani0712

![fragmentshtml](https://user-images.githubusercontent.com/72528017/111727953-e0258200-8839-11eb-9a6b-d7fdbf2aa10b.PNG)
![home-controller](https://user-images.githubusercontent.com/72528017/111727954-e0be1880-8839-11eb-92de-3ddf4c96dc37.PNG)
![indexgtml](https://user-images.githubusercontent.com/72528017/111727955-e0be1880-8839-11eb-8f59-8ed600642ac8.PNG)
![localhost_header](https://user-images.githubusercontent.com/72528017/111727957-e0be1880-8839-11eb-9e90-2942e7522074.PNG)
![styles css1](https://user-images.githubusercontent.com/72528017/111727958-e156af00-8839-11eb-9466-bd464f158184.PNG)
![styles css2](https://user-images.githubusercontent.com/72528017/111727960-e156af00-8839-11eb-9326-0bf0957d69d5.PNG)

2021-03-19 21:45 UTC, Rexzellius approved these changes
Has the necessary links.

2021-03-21 21:04 UTC, korina0430 requested changes
Did you mean to push all these .lock and .bin files? Please remove them and maybe add them to the git ignore file

2021-03-21 21:05 UTC, korina0430 commented on build/reports/tests/test/classes/org.launhcode.healthynutrition.HealthyNutritionApplicationTests.html
> +</div>
what does this file do? :o

2021-03-21 21:06 UTC, korina0430 reviewed
I am confused about the html and css files in the tests folder

2021-03-22 15:35 UTC, Dhwani0712 commented
> I am confused about the html and css files in the tests folder

I am not sure why they are showing in test file, I checked and they are in resources folder in Intellij

2021-03-22 23:24 UTC, closed without merging