Calorie tracking page
korina0430/liftoff pull request #18
Opened 2021-03-19 21:25 UTC by Rexzellius

<img width="266" alt="cod" src="https://user-images.githubusercontent.com/72165461/111843593-79eb3e80-88cf-11eb-8671-e038456a33b9.png">
<img width="1908" alt="cod3" src="https://user-images.githubusercontent.com/72165461/111843740-b5860880-88cf-11eb-8b9d-97130f138878.png">

2021-03-19 21:26 UTC, Rexzellius commented
> 
> 
> <img alt="cod" width="266" src="https://user-images.githubusercontent.com/72165461/111843593-79eb3e80-88cf-11eb-8671-e038456a33b9.png">
> 
> <img alt="cod3" width="1908" src="https://user-images.githubusercontent.com/72165461/111843740-b5860880-88cf-11eb-8b9d-97130f138878.png">

Done with DB & UI connections

2021-03-19 21:48 UTC, revathivarini approved these changes
Its awesome.

2021-03-21 21:08 UTC, korina0430 requested changes
please remove the bin and lock files from the pr

2021-03-21 21:09 UTC, korina0430 reviewed
It's really odd that there are bin files for all the classes you made, can you add .bin files to the git ignore?

2021-03-21 21:10 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/FoodController.java
> +//@Controller
can you delete this file since everything is commented out?

2021-03-21 21:10 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/MealController.java
> +// create a thymeleaf template that looks similar to the wiremock and return it from an endpoint in the controller
remove these comments

2021-03-21 21:11 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/MealController.java
> +//
remove

2021-03-21 21:11 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/MealController.java
> +//    List<Food> food = new ArrayList<>();
remove

2021-03-21 21:11 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/MealController.java
> +    @PostMapping("")
if the mapping is blank do you need ("")?

2021-03-21 21:12 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/MealController.java
> +// make if-elf or switch-case statements for calculations
If these need to be done in the future then make them todo comments!


//TODO: Make a method that stores user in put and calculates what they've entered.

Comments formatted in this way will be caught in code linters and highlighted in a specific way in intellij

2021-03-21 21:13 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/controllers/UserDayController.java
> +//public class UserDayController {
can you delete this file since it's all commented?

2021-03-21 21:13 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/Food.java
> +        private String breakfast;
indention is off here, please fix

2021-03-21 21:14 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/Meal.java
> +//    private boolean checkSkinType(String skinType, String facialType) {
this does not look related to the project, please delete

2021-03-21 21:14 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/User.java
> +//    public void setUsername(String username) {
can you delete this file?

2021-03-21 21:14 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/UserDay.java
> +//public class UserDay {
delete file

2021-03-21 21:14 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/data/FoodRepository.java
> +//import java.util.List;
delete this comment block please

2021-03-21 21:14 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/data/MealRepository.java
> +import java.util.List;
It doesn't seem like all these imports are used?

2021-03-21 21:15 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/data/UserDayRepository.java
> +//import java.util.Optional;
delete this file

2021-03-21 21:15 UTC, korina0430 commented on src/main/java/org/launhcode/healthynutrition/models/data/UserRepository.java
> +//@Repository
delete

2021-03-21 21:15 UTC, korina0430 commented on build/resources/main/templates/index.html
> +    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
stylesheets and scripts should be above any page content (like the h2)

2021-03-21 21:16 UTC, korina0430 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/liftoff
whats the difference between this file and the one here build/resources/main/application.properties???

2021-03-25 19:07 UTC, closed without merging